Restaurant Page
Deepakdanger/Restaurant_page pull request #1
Opened 2021-08-09 16:44 UTC by Deepakdanger

Here I build one restaurant website using Javascript. I have Used:-

- Use of webpack to bundle JavaScript application.
- Use tabbed browsing by navbar items.
- Use of different modules.

Here I have designed 3 pages: 1) Home  2) Menu   3) Contact

2021-08-09 21:17 UTC, SajjadAhmad14 commented on package.json
>    }
Please add the `webpack-dev-server` package as here as a dev dependency.

2021-08-09 21:20 UTC, SajjadAhmad14 requested changes
# Changes Required :recycle:
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hello, you have been doing a tremendous job so far :ok_hand:
## To Highlight 🎉
- [ ] Git flow is used properly.
- [ ] README file has instructions to run the project locally.

## To Improve 🙏
- [ ] Please see inline comments for refference.

# Optional


### Happy Coding ☺️

## If you have any questions you can comment here in this PR or can always connect with me on slack ( @Sajjad Ahmad ).

2021-08-09 21:20 UTC, SajjadAhmad14 commented on package.json
>    "author": "",
Please add all necessary run common commands like `build`, `development` should be in `package.json` inside `scripts'. 
```json
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },
```

2021-08-09 21:20 UTC, SajjadAhmad14 commented on README.md
> +## Live Demo Link
Please add an active link as this link is broken.

2021-08-11 08:37 UTC, rindrajosia approved these changes
Hi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

- [ ] Please consider using tools like Grammarly to help you with your grammar. Keep in mind that your readme is the first thing users check.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2021-08-11 08:37 UTC, rindrajosia commented on README.md
> +This project is a small restaurant app created using javascript.Here There is 3 pages home, menu and contact.
- [ ] [OPTIONAL] Please change it to: This project is a small restaurant app created using javascript. Here There are 3 pages home, menu and contact.

2021-08-11 09:20 UTC, merged